Repository SE701-T1/frontend, pull requests merged in 2022-04, with the labels that each got.

#149 fix failing test
  src/components/ChatHeader/__tests__/__snapshots__/ChatHeader.test.jsx.snap
Labels: Status: Review Needed, Type: Bug, Type: Maintenance, Priority: High

#148 Refactor pull_request_template.md
  .github/pull_request_template.md
Labels: Status: Review Needed, Type: Documentation, Priority: Low

#147 Fix CI workflow
  .github/workflows/react_testing.yml
Labels: Status: Review Needed, Type: Bug, Priority: Low

#143 Correct login carousel spelling and grammar errors
  src/pages/Login/Login.jsx
Labels: Status: Review Needed, Type: Maintenance, Priority: Low, Team: Users

#140 Redo of the upload styles since it was overwritten
  src/pages/Upload/UploadPage.jsx
  src/pages/Upload/UploadPage.module.css
Labels: Status: Review Needed, Type: Bug, Type: Feature, Priority: Low

#141 Issue #18 implement frontend of file upload
  src/components/UploadPopUp/UploadPopUp.jsx
  src/components/UploadPopUp/UploadPopUp.module.css
Labels: Status: Review Needed, Type: Feature

#152 Make the gap between course cards unclickable.
  src/components/CourseCard/CourseCard.jsx
  src/pages/Pairing/Pairing.jsx
Labels: Status: Review Needed, Type: Bug, Priority: Medium, Team: Pairing
