Repository SE701-T1/frontend, pull requests merged in 2022-03, with the labels that each got.

#3 Adding the issue template.
  .github/issue_template.md
Labels: Type: Documentation

#5 Docs: contributing guidelines
  CONTRIBUTING.md
Labels: Type: Documentation

#7 Docs: Add Code of Conduct Frontend
  CODE_OF_CONDUCT.md
Labels: Type: Documentation

#6 Adding the PR template.
  .github/pull_request_template.md
Labels: Type: Documentation

#34 Added react-test-renderer as dependency
  package-lock.json
  package.json
Labels: Type: Maintenance

#37 Fix eslint config for prettier-react.
  .eslintrc.json
Labels: Type: Bug, Priority: Critical

#39 Carousel component for the Splash Page
  package-lock.json
  package.json
  src/components/Carousel/Carousel.jsx
  src/components/Carousel/Carousel.module.css
  src/components/Carousel/Page.jsx
  src/components/Carousel/Page.module.css
  src/components/Carousel/__tests__/Carousel.test.js
  src/components/Carousel/__tests__/Page.test.js
  src/components/Carousel/__tests__/__snapshots__/Carousel.test.js.snap
  src/components/Carousel/__tests__/__snapshots__/Page.test.js.snap
Labels: Type: Feature

#38 35 profile badge
  src/components/ProfileBadge/ProfileBadge.jsx
  src/components/ProfileBadge/_tests_/ProfileBadge.test.jsx
Labels: Type: Feature

#40 feat: pwa configuration
  package-lock.json
  package.json
  src/context/serviceWorkerContext.jsx
  src/index.jsx
  src/reportWebVitals.js
  src/service-worker.js
  src/serviceWorkerRegistration.js
Labels: Type: Feature

#42 Feat: navigation components
  package-lock.json
  package.json
  src/App.jsx
  src/assets/menu-icons/accounts.svg
  src/assets/menu-icons/chat.svg
  src/assets/menu-icons/courses.svg
  src/assets/menu-icons/find-matches.svg
  src/assets/menu-icons/logo.svg
  src/components/NavBar/Nav.jsx
  src/components/NavBar/Nav.module.css
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/SideBar.jsx
  src/components/NavBar/__tests__/Nav.test.jsx
  src/components/NavBar/__tests__/NavBar.test.jsx
  src/components/NavBar/__tests__/SideBar.test.jsx
  src/components/NavBar/index.js
  src/components/Theme/Theme.jsx
  src/components/Theme/index.js
  src/pages/Routes/Routes.jsx
Labels: Type: Feature

#49 Feat: Timetable upload page
  src/components/Timetable/UploadPage.jsx
  src/components/Timetable/UploadPage.module.css
  src/components/Timetable/__tests__/UploadPage.test.jsx
  src/components/Timetable/index.js
Labels: Type: Feature

#51 Re merge Course card component
  src/components/CourseCard/CourseCard.jsx
  src/components/CourseCard/CourseCard.module.css
  src/components/CourseCard/_tests_/CourseCard.test.jsx
Labels: Type: Feature

#58 BUG: UploadPage component test warnings
  src/components/Timetable/__tests__/UploadPage.test.jsx
Labels: Type: Bug

#57 fix: fixed the test for Course Card Component
  src/components/CourseCard/_tests_/CourseCard.test.jsx
Labels: Status: Review Needed, Type: Bug, Priority: High

#60 add no console warning to Pwa files
  src/context/serviceWorkerContext.jsx
  src/serviceWorkerRegistration.js
Labels: Status: Review Needed, Type: Maintenance

#53 User search component
  src/components/UserSearch/UserSearch.jsx
  src/components/UserSearch/UserSearch.module.css
  src/components/UserSearch/__tests__/UserSearch.test.jsx
Labels: Type: Feature

#61 Feature: Global authentication context
  package-lock.json
  package.json
  src/App.jsx
  src/context/authContext.jsx
Labels: Type: Feature

#50 Feat: MessageBubble Component
  src/components/MessageBubble/MessageBubble.jsx
  src/components/MessageBubble/MessageBubble.module.css
  src/components/MessageBubble/__tests__/MessageBubble.test.jsx
  src/components/MessageBubble/__tests__/__snapshots__/MessageBubble.test.jsx.snap
  src/components/MessageBubble/index.js
Labels: Status: Review Needed, Status: Revision Needed, Type: Feature

#44 Feature: Login button
  .env.example
  .gitignore
  package-lock.json
  package.json
  public/env.js
  public/index.html
  src/pages/Login/LoginButton.jsx
  src/pages/Login/LoginButton.module.css
  src/pages/Login/__tests__/LoginButton.test.jsx
Labels: Type: Feature

#63 Chat list component
  src/Util/TimeFormater.js
  src/components/ChatList/ChatList.jsx
  src/components/ChatList/ChatList.module.css
  src/components/ChatList/ChatListItem.jsx
  src/components/ChatList/ChatListItem.module.css
  src/components/ChatList/__tests__/ChatList.test.jsx
  src/components/ChatList/__tests__/ChatListItem.test.jsx
  src/components/ChatList/__tests__/__snapshots__/ChatListItem.test.jsx.snap
  src/components/ProfileBadge/ProfileBadge.jsx
Labels: Type: Feature

#52 Created loading component and related file
  src/components/Loading/Loading.module.css
  src/components/Loading/LoadingComponent.jsx
  src/components/Loading/__tests__/LoadingComponent.test.jsx
Labels: Type: Feature

#62 Chat input compnent
  package.json
  src/components/Carousel/__tests__/Carousel.test.js
  src/components/Carousel/__tests__/Page.test.js
  src/components/ChatInput/ChatInput.jsx
  src/components/ChatInput/ChatInput.module.css
  src/components/ChatInput/__tests__/ChatInput.test.jsx
  src/components/ChatInput/__tests__/__snapshots__/ChatInput.test.jsx.snap
Labels: Type: Feature

#67 ChatBuddyDetail Component
  src/components/Carousel/__tests__/__snapshots__/Carousel.test.js.snap
  src/components/Carousel/__tests__/__snapshots__/Page.test.js.snap
  src/components/ChatBuddyDetail/ChatBuddyDetail.jsx
  src/components/ChatBuddyDetail/ChatBuddyDetail.module.css
  src/components/ChatBuddyDetail/__tests__/ChatBuddyDetail.test.jsx
  src/components/ChatBuddyDetail/__tests__/__snapshots__/ChatBuddyDetail.test.jsx.snap
  src/components/ChatBuddyDetail/index.js
  src/components/ChatList/__tests__/ChatList.test.jsx
  src/components/ChatList/__tests__/__snapshots__/ChatListItem.test.jsx.snap
  src/components/MessageBubble/__tests__/MessageBubble.test.jsx
  src/components/ProfileBadge/ProfileBadge.jsx
  src/components/ProfileBadge/index.js
  src/components/Theme/Theme.jsx
Labels: Type: Feature

#69 Conversation dialogues list component
  src/components/DialoguesList/DialoguesList.jsx
  src/components/DialoguesList/DialoguesList.module.css
  src/components/DialoguesList/__tests__/DialoguesList.test.jsx
  src/components/DialoguesList/__tests__/__snapshots__/DialoguesList.test.jsx.snap
  src/components/UserSearch/UserSearch.jsx
Labels: Type: Feature

#70 Login page
  src/components/Carousel/Page.module.css
  src/components/Carousel/__tests__/__snapshots__/Carousel.test.js.snap
  src/components/Carousel/__tests__/__snapshots__/Page.test.js.snap
  src/pages/Login/Login.jsx
  src/pages/Login/Login.module.css
  src/pages/Login/LoginButton.jsx
  src/pages/Login/__tests__/LoginButton.test.jsx
Labels: Status: Review Needed, Type: Feature, Priority: High, Team: Users

#77 Added API stubs
  src/api/CommunicationAPI.js
  src/api/PairingAPI.js
  src/api/TimetableAPI.js
  src/api/UserAPI.js
Labels: Type: Feature, Team: Messaging

#76 Feature: Automate request authorization header
  package-lock.json
  package.json
  src/context/authContext.jsx
Labels: Type: Feature, Team: Users

#72 ChatHeader Component
  src/components/ChatHeader/ChatHeader.jsx
  src/components/ChatHeader/ChatHeader.module.css
  src/components/ChatHeader/__tests__/ChatHeader.test.jsx
  src/components/ChatHeader/__tests__/__snapshots__/ChatHeader.test.jsx.snap
  src/components/ChatHeader/index.js
Labels: Status: Review Needed, Type: Feature, Team: Messaging

#79 Feature: React route middleware
  src/pages/Routes/AuthRoutes.jsx
  src/pages/Routes/__tests__/AuthRoutes.test.jsx
Labels: Type: Feature, Team: Users

#86 Pairing page
  .eslintrc.json
  src/components/CourseCard/CourseCard.jsx
  src/components/CourseCard/CourseCard.module.css
  src/components/CourseCard/_tests_/CourseCard.test.jsx
  src/pages/Pairing/Pairing.jsx
  src/pages/Pairing/Pairing.module.css
  src/pages/Pairing/__tests__/Pairing.test.jsx
  src/pages/Routes/Routes.jsx
Labels: Status: Review Needed, Type: Feature, Priority: High, Team: Messaging

#90 Feature: Configure auth routes
  src/context/authContext.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/LoginButton.jsx
  src/pages/Routes/AuthRoute.jsx
  src/pages/Routes/Routes.jsx
  src/pages/Routes/__tests__/AuthRoutes.test.jsx
  src/pages/Routes/__tests__/Routes.test.jsx
Labels: Type: Feature, Team: Users

#93 Socket setup
  package.json
  src/App.jsx
  src/api/sockets/Sockets.js
  src/components/Example/Example.jsx
  src/context/authContext.jsx
  src/pages/Dashboard/Dashboard.jsx
Labels: Type: Feature, Type: Maintenance, Priority: High, Team: Messaging

#92 Organise Chat Page
  src/components/ChatList/ChatList.jsx
  src/components/ChatList/ChatList.module.css
  src/components/ChatList/ChatListItem.module.css
  src/components/DialoguesList/DialoguesList.jsx
  src/components/DialoguesList/DialoguesList.module.css
  src/components/DialoguesList/__tests__/__snapshots__/DialoguesList.test.jsx.snap
  src/components/MessageBubble/MessageBubble.jsx
  src/components/MessageBubble/MessageBubble.module.css
  src/components/MessageBubble/__tests__/__snapshots__/MessageBubble.test.jsx.snap
  src/components/UserSearch/UserSearch.jsx
  src/components/UserSearch/UserSearch.module.css
  src/pages/Chat/Chat.jsx
  src/pages/Chat/Chat.module.css
  src/pages/Routes/Routes.jsx
Labels: Status: In Progress, Type: Feature, Team: Messaging

#91 Scaffold Courses Page
  src/components/Timetable/BuddyCard.jsx
  src/components/Timetable/BuddyCard.module.css
  src/components/Timetable/CoursesPageCard.jsx
  src/components/Timetable/CoursesPageCard.module.css
  src/components/Timetable/__tests__/BuddyCard.test.jsx
  src/components/Timetable/__tests__/CoursesPageCard.test.jsx
Labels: Status: Review Needed, Type: Feature, Priority: Medium

#97 API Functions
  .env.example
  package-lock.json
  package.json
  src/App.jsx
  src/api/APIUtils.js
  src/api/CommunicationAPI.js
  src/api/PairingAPI.js
  src/api/TimetableAPI.js
  src/api/UserAPI.js
  src/api/sockets/Sockets.js
  src/api/sockets/Sockets.jsx
  src/context/authContext.jsx
  src/pages/Routes/GoogleRedirectRoute.jsx
  src/pages/Routes/Routes.jsx
Labels: Type: Feature, Team: Messaging

#100 Edit contributing guidelines
  CONTRIBUTING.md
Labels: Type: Documentation

#112 Feat link url input
  src/api/TimetableAPI.js
  src/components/Timetable/__tests__/UploadPage.test.jsx
  src/pages/Upload/UploadPage.jsx
  src/pages/Upload/UploadPage.module.css
  src/pages/Upload/__tests__/UploadPage.test.jsx
Labels: Type: Feature

#85 Settings Page (Includes a toggle pairing button)
  src/pages/Settings/Settings.jsx
  src/pages/Settings/Settings.module.css
  src/pages/Settings/__tests__/Settings.test.jsx
Labels: Status: Completed, Type: Feature, Priority: Low, Team: Users

#126 Bug: Fixed tests in Settings page
  src/pages/Settings/__tests__/Settings.test.jsx
  src/pages/Settings/__tests__/__snapshots__/Settings.test.jsx.snap
Labels: Type: Bug

#124 add link to wiki
  CONTRIBUTING.md
Labels: Type: Documentation

#127 Feature: Integrating settings page
  src/assets/menu-icons/accounts.svg
  src/assets/menu-icons/settings.svg
  src/components/NavBar/SideBar.jsx
  src/components/NavBar/__tests__/SideBar.test.jsx
  src/pages/Routes/Routes.jsx
  src/pages/Settings/Settings.jsx
  src/pages/Settings/Settings.module.css
  src/pages/Settings/__tests__/__snapshots__/Settings.test.jsx.snap
Labels: Type: Feature

#128 Documentation: Update default README.md
  README.md
Labels: Type: Documentation

#132 Fix up minor UI glitches for the Demo
  src/components/ChatBuddyDetail/ChatBuddyDetail.jsx
  src/components/ChatInput/ChatInput.jsx
  src/components/ChatInput/__tests__/__snapshots__/ChatInput.test.jsx.snap
  src/components/ChatList/ChatList.jsx
  src/components/ChatList/ChatListItem.jsx
  src/components/UserSearch/UserSearch.jsx
  src/pages/Chat/Chat.jsx
Labels: Type: Feature, Priority: Critical

#134 Fix up text for demo and Add Favicon
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/components/PopUp/PopUp.module.css
Labels: Priority: Critical, Team: Pairing

#138 Upload page styles
  package-lock.json
  src/pages/Upload/UploadPage.jsx
  src/pages/Upload/UploadPage.module.css
Labels: Status: Review Needed, Type: Feature, Priority: Low

#139 Added Snackbar when no buddies are found for pair.
  src/pages/Pairing/Pairing.jsx
Labels: Status: Review Needed, Type: Feature, Priority: Low, Team: Messaging

#137 add logout button && no more matches for pairing popup && upload popup
  src/assets/menu-icons/logout.svg
  src/components/NavBar/SideBar.jsx
  src/components/NavBar/__tests__/__snapshots__/Nav.test.jsx.snap
  src/components/NoBuddy/NoBuddy.jsx
  src/components/NoBuddy/NoBuddy.module.css
  src/components/UploadPopUp/UploadPopUp.jsx
  src/components/UploadPopUp/UploadPopUp.module.css
  src/pages/Login/LoginButton.jsx
  src/pages/Logout/Logout.jsx
  src/pages/Pairing/Pairing.jsx
  src/pages/Routes/Routes.jsx
  src/pages/Upload/UploadPage.jsx
Labels: Status: Review Needed, Type: Feature, Type: Maintenance, Priority: Low, Priority: Medium
